apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbixpsk
  labels:
    app: zabbix
    tier: proxy
  namespace: zabbix
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
